### ISSUE TITLE
Add support for AW2725DF?

### ISSUE THREAD

**Issue by jjcodestuff** [Fefedu973/AW3423DWF-SignalRGB-Plugin#1]
Hello!

Wondering if its possible to add support for the new [AW2725DF](https://www.dell.com/en-us/shop/alienware-27-360hz-qd-oled-gaming-monitor-aw2725df/apd/210-bljd/monitors-monitor-accessories). 

Everything about the firmware seems the same. Let me know what information I can get you to do this. 

Also, is there any progress on SignalRGB adding this plugin natively?

Thanks!

**Comment by Fefedu973** [comment]
I can try to add support for it by I will need more infos. Like USB Pcap wireshark captures, and say me if you find your device in the subfolders of this directory inside the regedit "\HKEY_LOCAL_MACHINE\SOFTWARE\Alienware\System\AFXCapableDevices" If yes please give me the communication dll that is given

As for adding this plugin natively this is not planned right now because it is not working well right now (low fps) You can ask Doro on the signal RGB server if you need more infos.
